<a href="https://colab.research.google.com/github/Aditi-Adri/Data_Structures_In_Python/blob/main/Array_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Linear Array

In [1]:
import numpy as np

In [ ]:
# create

ar = np.zeros (10,dtype=float)
print(ar)
ar = np.array ([1,2,3,4,5])
print(ar)
print(ar.dtype)
print(ar.size)
arr = np.random.randint(45, size=10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 2 3 4 5]
int64
5
[25  4  0  8  2 15 21 43 20 18]


In [ ]:
# left shift

arr = np.array([1,2,3,4,5], dtype=int)
print("Before Left Shifting:",arr)

def leftShift(arr):
    for i in range (len(arr)-1) :
      arr[i] = arr[i+1]
    arr[len(arr)-1] = 0

leftShift(arr)
print("After Left Shifting :",arr)

Before Left Shifting: [1 2 3 4 5]
After Left Shifting : [2 3 4 5 0]


In [ ]:
# right shift

arr = np.array([1,2,3,4,5], dtype=int)
print("Before Right Shifting:",arr)

def rightShift (arr) :
  for i in range (len(arr)-1,0,-1) :
    arr[i] = arr[i-1]
  arr[0] = 0

rightShift(arr)
print("After Right Shifting :",arr)

Before Right Shifting: [1 2 3 4 5]
After Right Shifting : [0 1 2 3 4]


In [ ]:
# remove
# left shift

arr = np.array([1,2,3,4,5], dtype=int)
print("Before removal:",arr)

def remove (arr,ind) :
  for i in range (ind,len(arr)-1) :
    arr[i] = arr[i+1]
  arr[len(arr)-1] = 0

remove(arr,2)
print("After removing element at index 2:",arr)

Before removal: [1 2 3 4 5]
After removing element at index 2: [1 2 4 5 0]


In [ ]:
# insert
# right shift

arr = np.array([1,2,3,4,5,0,0], dtype=int)
print("Before insertion:",arr)

def insert (arr,ind,elem) :
  for i in range (len(arr)-1,ind,-1) :
    arr[i] = arr[i-1]
  arr[ind] = elem

insert(arr, 2, 999)
print("After inserting element at index 2:",arr)

Before insertion: [1 2 3 4 5 0 0]
After inserting element at index 2: [  1   2 999   3   4   5   0]


In [ ]:
# left rotate

arr = np.array([1,2,3,4,5,6])
print(arr)

def left_rotate (arr) :
  temp = arr[0]
  leftShift(arr)
  arr[len(arr)-1] = temp

left_rotate(arr)
print(arr)

[1 2 3 4 5 6]
[2 3 4 5 6 1]


In [ ]:
# right rotate

arr = np.array([1,2,3,4,5,6])
print(arr)

def right_rotate (arr) :
  temp = arr[len(arr)-1]
  rightShift(arr)
  arr[0] = temp

right_rotate(arr)
print(arr)

[1 2 3 4 5 6]
[6 1 2 3 4 5]


In [ ]:
# insert when array in full

def insert_at (arr,ind,elem) :
  ar = np.zeros(len(arr)+1,dtype=arr.dtype)
  for i in range (len(arr)) :
    ar[i] = arr[i]
  insert (ar,ind,elem)
  return ar

arr = np.array ([1,2,3,4,5])
print(arr)
ar = insert_at (arr,2,999)
print(ar)

[1 2 3 4 5]
[  1   2 999   3   4   5]


In [ ]:
# BINARY SEARCH
# in sorted array

def bin_search (ar,elem) :
  left , right = 0 , len(ar)-1
  while left <= right :
    mid = (left+right)//2
    if ar[mid] == elem :
      return mid
    elif elem > ar[mid] :
      left = mid + 1
    else :
      right = mid - 1
  return -1

#       index          0  1  2  3  4   5   6   7   8   9   10  11  12  13  14  15  16
sorted_arr = np.array([1, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59])
elem = 37
idx = bin_search(sorted_arr, elem)
print(f"{elem} was found at index {idx}")

37 was found at index 11


### Multi Dimentional Array

In [ ]:
arr2D = np.array( [[1,2,4,6],[5,6,7,8],[9,0,1,2]] )
print(arr2D)
print("First Row",arr2D[0])
print("Second Row",arr2D[1])
print("Third Cell",arr2D[0][2])

ar = np.zeros (shape=(3,4),dtype=int)
total = ar.size
r , c = ar.shape
print ("Total cell",total)

[[1 2 4 6]
 [5 6 7 8]
 [9 0 1 2]]
First Row [1 2 4 6]
Second Row [5 6 7 8]
Third Cell 4
Total cell 12


In [ ]:
ar = np.array ([ [1,2,3,4],[5,6,7,8] ])
r,c = ar.shape

for i in range (r) :
  for j in range (c) :
    print(ar[i][j],end=" ")
  print()

for i in range (c) :
  for j in range (r) :
    print(ar[j][i],end=" ")
  print()

print(ar)
print(ar.T)

1 2 3 4 
5 6 7 8 
1 5 
2 6 
3 7 
4 8 
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
# transpose

tr = np.zeros((c,r),dtype=int)
for i in range (r) :
  for j in range (c) :
    tr[j][i] = ar[i][j]
print(tr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
# Transpose in place
#

def trans (ar) :
  r , c = ar.shape

  if r != c :
    return "Not possible"

  for i in range (r) :
    for j in range (i+1,c) :
      ar[i][j] ,ar[j][i] = ar[j][i] , ar[i][j]
  return ar


a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(a)
print(trans(a))

In [ ]:
ar = np.array ([ [1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17] ])
print(ar)
r,c = ar.shape
print("Primary Diagonal : ")
for i in range (r) :
  for j in range (c) :
    if i == j :
      print(ar[i][i],end=" ")
print()
print("Secondary diagonal : ")
for i in range (r) :
  for j in range (c) :
    if i == c-1-j :
      print(ar[i][j],end=" ")
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]
 [14 15 16 17]]
Primary Diagonal : 
1 6 12 17 
Secondary diagonal : 
4 7 11 14 


In [ ]:
# clockwise rotate the boundaries :
#     1. transpose the matrix
#     2. reverse the row

# clockwise rotate the boundaries :
#     1. transpose the matrix
#     2. reverse the column


In [ ]:
#

def rotate (ar) :
  r , c = ar.shape

  for i in range (r) :
    for j in range (i+1,r) :
      ar[i][j] ,ar[j][i] = ar[j][i] , ar[i][j]


  for i in range (r) :
    for j in range (r//2) :
      ar[i][j],ar[i][r-1-j] = ar[i][r-1-j] ,ar[i][j]


  return ar


a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
# a = np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16] ])
print(a)
print(rotate(a))

In [ ]:
# 9

def rotate (ar) :
  r , c = ar.shape

  for i in range (r) :
    for j in range (i+1,r) :
      ar[i][j] ,ar[j][i] = ar[j][i] , ar[i][j]


  for i in range (r) :
    for j in range (r//2) :
      ar[j][i],ar[r-1-j][i] = ar[r-1-j][i] ,ar[j][i]


  return ar


# a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
a = np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16] ])
print(a)
print(rotate(a))

In [ ]:
# boundary items

a = np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16] ])
print(a)

def bound (ar) :
  r , c = ar.shape
  n = (c*2)+ (2*r-4)
  k = 0
  new = np.array([0]*n)

  for i in range (r) :
    for j in range (c) :
      if i == 0 :
        new[k] = ar[i][j]
        k += 1
      if i != 0 and i != r-1 and j == c-1 :
        new[k] = ar[i][j]
        k += 1
      if i == r-1   :
        new[k] = ar[r-1][c-1-j]
        k += 1

  for i in range (r) :
    if i != 0 and i != r-1 :
      new[k] = ar[c-1-i][0]
      k += 1


  return new


print(bound(a))



In [ ]:
# multiplication

a = np.array([ [1,2,3],[4,5,6] ])
b = np.array([ [10,11],[20,21],[30,31] ])

r1 , c1 = a.shape
r2 , c2 = b.shape

if r1 != c2  :
  print("Not possible")

new = np.zeros ((r1,c2),dtype=int)

for i in range (r1) :
  for j in range (c2) :
    for k in range (c1) :
      new[i][j] += a[i][k]*b[k][j]

print(new)
